file_format: "1"
id: redongle
name: Redongle
type: shield
url: https://github.com/jleonardocosa/redongle
requires: [pro_micro]
features:
  - keys
siblings:
  - redongle_left
  - redongle_right
  - redongle_dongle
